---
# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

# Can be removed if link is everywhere. Link is needed for scripts,
# e.g. zabbix-check-upgradeable-packages-pkgs
- name: Check if /usr/local/etc/zabbix/zabbix_agentd.conf is a symbolic link
  ansible.builtin.command: test -s /usr/local/etc/zabbix/zabbix_agentd.conf
  changed_when: false

- name: Set is_jail
  ansible.builtin.set_fact:
    is_jail: "{{ 'jails' in ansible_virtualization_tech_guest }}"

- name: Copy sudo rules for freebsd-update
  ansible.builtin.copy:
    src: FreeBSD/sudoers.d/local-mit-zabbix-agent-check-upgrades
    dest: /usr/local/etc/sudoers.d/
    mode: "0440"
    validate: visudo -cf %s

# User zabbix needs a home in order to download vulnxml (even if --file is
# give we get "pkg: pkg_audit_fetch(open out fd): Permission denied")
# The problem might be that /var/cache/zabbix/pkg-audit is for unknown
# reason "-r--r--r--" - needs more investigation.
- name: Create /var/cache/zabbix
  ansible.builtin.file:
    path: /var/cache/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: "755"

# - name: Give user zabbix a home
#  ansible.builtin.user:
#    name: zabbix
#    home: /var/cache/zabbix
#    skeleton: /var/empty
#    # https://github.com/ansible/ansible/issues/6854
#  changed_when: no

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Add zabbix-agent configuration file
  ansible.builtin.copy:
    src: FreeBSD/local-userparameter_check-upgrades.conf
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: "0644"
  notify: Restart zabbix-agent

- name: Add mit-zabbix-lld-no-agent-jails.conf
  ansible.builtin.template:
    src: FreeBSD/mit-zabbix-lld-no-agent-jails.conf
    dest: /usr/local/etc/zabbix/mit-zabbix-lld-no-agent-jails.conf
    mode: "0644"

- name: Install checkrestart
  ansible.builtin.package:
    name: checkrestart
    state: present

# - name: Copy /etc/cron.d/local-zabbix-check-upgrades
#   copy: src=cron.d-local-zabbix-check-upgrades dest=/etc/cron.d/local-zabbix-check-upgrades
- name: Copy binaries
  ansible.builtin.copy:
    src: FreeBSD/{{ item }}
    dest: /opt/bin/
    mode: "0755"
  loop:
    - needrestart
    - zabbix-check-upgradeable-packages-pkgs
    - zabbix-checkrestart-service

- name: Copy binaries (no jails)
  ansible.builtin.copy:
    src: FreeBSD/{{ item }}
    dest: /opt/bin/
    mode: "0755"
  loop:
    - zabbix-check-upgradeable-packages-system
    - zabbix-checkrestart-kernel
    - zabbix-lld-jail-bases
    - zabbix-lld-no-agent-jails
  when: not is_jail

# As state is not supported by ansible.builtin.template we remove the files here.
- name: Remove deprecated files on jail
  ansible.builtin.file:
    path: /opt/bin/{{ item }}
    state: "absent"
  loop:
    - zabbix-checkrestart-kernel
    - zabbix-check-upgradeable-packages-system
  when: is_jail

- name: Add cron for zabbix-checkrestart-kernel
  ansible.builtin.cron:
    user: zabbix
    name: Check if kernel needs a restart
    # special_time: hourly - save ressources, we only need this at working time
    minute: 55
    hour: 6-17
    job: /opt/bin/zabbix-checkrestart-kernel
    state: "{{ 'absent' if (is_jail) else 'present' }}"

- name: Add cron for zabbix-checkrestart-service
  ansible.builtin.cron:
    user: zabbix
    name: Check if service needs a restart
    # special_time: hourly - save ressources, we only need this at working time
    minute: 56
    hour: 6-17
    job: /opt/bin/zabbix-checkrestart-service

- name: Add cron for zabbix-check-upgradeable-packages-system
  ansible.builtin.cron:
    user: zabbix
    name: Check if there are upgradeable system packages
    # special_time: hourly - save ressources, we only need this at working time
    minute: 57
    hour: 6-17
    job: /opt/bin/zabbix-check-upgradeable-packages-system
    state: "{{ 'absent' if (is_jail) else 'present' }}"

- name: Add cron for zabbix-check-upgradeable-packages-pkgs
  ansible.builtin.cron:
    user: zabbix
    name: Check if there are upgradeable packages
    # special_time: hourly - save ressources, we only need this at working time
    minute: 58
    hour: 6-17
    job: /opt/bin/zabbix-check-upgradeable-packages-pkgs

- name: Logcheck rules
  # Security Events for sudo
  # The file has to be named "local", either "a", "0-mit-zabbix-agent-check-upgrades"
  # or "mit-zabbix-agent-check-upgrades" do not work. Test with:
  # sudo -u logcheck logcheck -o -t -d -l /var/log/auth.log
  ansible.builtin.lineinfile:
    create: true
    path: /usr/local/etc/logcheck/violations.ignore.d/local
    line: "^\\w{3} [ :0-9]{11} [._[:alnum:]-]+ sudo:   root : PWD=.* ; USER=zabbix ; COMMAND=\\/opt\\/bin\\/zabbix-checkrestart-service"
    mode: "644"
  when: "'logcheck' in ansible_facts.packages"

- name: Remove deprecated files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/bin/zabbix-checkrestart
    - /usr/local/etc/periodic/daily/900.zabbix-checkrestart
    - /usr/local/bin/needrestart
    - /usr/local/bin/zabbix-checkrestart
    - /usr/local/bin/zabbix-check-upgradeable-packages
    - /usr/local/bin/zabbix-lld-jail-bases
