---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

# We use ansible_lsb.id instead of ansible_distribution as this adds support for
# UCS (Univention Corporate Server) which reports ansible_distribution=Debian and
# ansible_lsb.id=Univention
- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_system }}-{{ ansible_lsb.id }}_{{ ansible_lsb.major_release }}.yml"
    - "default.yml"

- name: Copy sudo rules for needrestart
  copy: >
    src=sudoers.d-local-mit-zabbix-agent-check-upgrades
    dest=/etc/sudoers.d/local-mit-zabbix-agent-check-upgrades
    validate='visudo -cf %s'

- name: Add zabbix-agent configuration file
  copy: src=local-userparameter_check-upgrades.conf
        dest={{ zabbix_agent_conf_dir }}
        mode=0644
  notify: restart zabbix-agent
  become: yes

- name: Copy /usr/local/sbin/zabbix-check-upgrades
  copy: src=zabbix-check-upgrades dest=/usr/local/sbin/zabbix-check-upgrades mode=0755

- name: Copy /etc/cron.d/local-zabbix-check-upgrades
  copy: src=cron.d-local-zabbix-check-upgrades dest=/etc/cron.d/local-zabbix-check-upgrades
  when: "'kcvmsrv3' not in inventory_hostname"

- name: Remove deprecated /var/lib/misc/zabbix-check-upgrades-dpkg-log.sha1
  file: path=/var/lib/misc/zabbix-check-upgrades-dpkg-log.sha1 state=absent

