---
# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

- name: Include ansible_system.yml
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
