---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

# We use ansible_lsb.id instead of ansible_distribution as this adds support for
# UCS (Univention Corporate Server) which reports ansible_distribution=Debian and
# ansible_lsb.id=Univention
- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_system }}-{{ ansible_lsb.id }}_{{ ansible_lsb.major_release }}.yml"
    - "default.yml"
  when: ansible_lsb is defined and ansible_lsb.id is defined

# Ansible 2: with_first_found is always evaluated even if "when: false"
# https://github.com/ansible/ansible/issues/13552
- include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_system }}-{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "default.yml"
      skip: true
  when: ansible_lsb is not defined or ansible_lsb.id is not defined

