---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

- name: Copy sudo rules for syspatch
  copy:
    src: OpenBSD/sudoers.d/local-mit-zabbix-agent-check-upgrades
    dest: /etc/sudoers.d/local-mit-zabbix-agent-check-upgrades
    mode: 0440
    validate: 'visudo -cf %s'

- name: Add zabbix-agent configuration file
  copy:
    src: OpenBSD/local-userparameter_check-upgrades.conf
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: 0644
  notify: Restart zabbix-agent
  become: yes

- name: Install checkrestart
  package:
    name: checkrestart
    state: present

#- name: Copy /etc/cron.d/local-zabbix-check-upgrades
#  copy: src=cron.d-local-zabbix-check-upgrades dest=/etc/cron.d/local-zabbix-check-upgrades
- name: Copy binary to /usr/local/bin/
  copy:
    src: OpenBSD/{{ item }}
    dest: /usr/local/bin/
    mode: 0755
  loop:
    - zabbix-checkrestart

- name: Add cron for zabbix-checkrestart
  ansible.builtin.cron:
    user: _zabbix
    name: Check if service needs a restart
    #special_time: hourly - save ressources, we only need this at working time
    minute: 55
    hour: 6-17
    job: /usr/local/bin/zabbix-checkrestart

