#!/bin/bash
#
# Distributed via ansible - mit.zabbix-agent.check-upgrades
#
# v2021-08-26-1
#
# grep -q RESTART_SERVICES /etc/default/mit-check-upgrades || echo "RESTART_SERVICES=yes" | sudo tee -a /etc/default/mit-check-upgrades
# grep -q AUTOMATIC_REBOOT /etc/default/mit-check-upgrades || echo "AUTOMATIC_REBOOT=yes" | sudo tee -a /etc/default/mit-check-upgrades

RESTART_SERVICES_ONLY_AT_REBOOT_TIME=no
# Reboot only on days equal or less than 5 (Friday)
REBOOT_DAY=5
# Reboot if hour of day is equal or above 0
REBOOT_HOUR_MIN=0
# Reboot if hour of day is equal or less than 6
REBOOT_HOUR_MAX=6

[ -r /etc/default/mit-check-upgrades ] && . /etc/default/mit-check-upgrades

# Check at least every 360 minutes and at max every 60
DEL_TIME=$(((REBOOT_HOUR_MAX-REBOOT_HOUR_MIN)*60))
DEL_TIME=$(($DEL_TIME>360?360:$DEL_TIME))

#20814: needrestart meldet "Unable to get Terminal Size"
export COLUMNS=80
export LINES=30

# Delete file if older than DEL_TIME in order to force a complete check.
[ -f /var/lib/misc/zabbix-check-upgrades-dpkg-log ] && \
    find /var/lib/misc/zabbix-check-upgrades-dpkg-log -mmin +${DEL_TIME} -delete

# Only run if dpkg.log has changed
if [ /var/log/dpkg.log -ot /var/lib/misc/zabbix-check-upgrades-dpkg-log ]; then
    #echo "No changes in /var/log/dpkg.log"
    exit 0
fi

touch /var/lib/misc/zabbix-check-upgrades-dpkg-log

DAY=$(date +%u)
HOUR=$(date +%H)

function restart_services {
    # First we use needrestart as needrestart has its own special handling of
    # special services like systemd-manager, see 
    # /etc/needrestart/restart.d/README.needrestart
    /usr/sbin/needrestart -q -r a -l 1>/dev/null
    # Then we use systemctl / service for restarting services needrestart 
    # skips ("Service restarts being deferred: systemd-logind.service")
    for service in $(/usr/sbin/needrestart -b -r l -l | awk ' /NEEDRESTART-SVC: / { print $2; }'); do
        logger -t $0 "Restarting $service"
        if [ -f /bin/systemctl ]; then
            systemctl restart $service
        else
            /usr/sbin/service $service restart
        fi
    done
}

if [ "${RESTART_SERVICES}" = "yes" ]; then
    NEEDRESTARTSVC=$(/usr/sbin/needrestart -b -r l -l | awk ' /NEEDRESTART-SVC: / { print $2; }')
    if [ -n "$NEEDRESTARTSVC" ]; then
        if [ ${RESTART_SERVICES_ONLY_AT_REBOOT_TIME} == "yes" ]; then
            if [ ${DAY} -le ${REBOOT_DAY} ] \
                    && [ ${HOUR} -ge ${REBOOT_HOUR_MIN}  ] \
                    && [ ${HOUR} -le ${REBOOT_HOUR_MAX} ] ; then
                restart_services
            fi
        else
            restart_services
        fi
    fi
fi

VALUE="$(/usr/sbin/needrestart -b -r l -l | awk ' /NEEDRESTART-SVC: / { print $2; }' | tr "\n" "," | sed 's/,$//')"
/usr/bin/zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k "system.sw.needrestart.library" -o "${VALUE}" 1>/dev/null

if [ "${AUTOMATIC_REBOOT}" = "yes" ]; then
    NEEDRESTART_KSTA=$(/usr/sbin/needrestart -b -r l -k | awk ' /NEEDRESTART-KSTA:/ { print $2; }')
    if [ ! -z "${NEEDRESTART_KSTA}" ]; then
        if [ ${NEEDRESTART_KSTA} -gt 1 ] && [ ${DAY} -le ${REBOOT_DAY} ] \
                && [ ${HOUR} -ge ${REBOOT_HOUR_MIN}  ] && [ ${HOUR} -le ${REBOOT_HOUR_MAX} ] ; then
            logger -t $0 "Restarting system (reboot)"
            /sbin/reboot
        fi
    else
        # No problem if running in a linux container (mfs1)
        if ! tr '\0' '\n' < /proc/1/environ | grep -q "container=lxc"; then
            echo "No NEEDRESTART-KSTA from needrestart"
        fi
    fi
fi

