#!/bin/bash
#
# Distributed via ansible - mit.zabbix-agent.check-upgrades
#
# echo "RESTART_SERVICES=yes" | sudo tee -a /etc/default/mit-check-upgrades
# echo "AUTOMATIC_REBOOT=yes" | sudo tee -a /etc/default/mit-check-upgrades

if [ -f /etc/default/mit-check-upgrades ]; then
    . /etc/default/mit-check-upgrades
fi

# Delete file if older than 6 hours in order to force a complete check.
[ -f /var/lib/misc/zabbix-check-upgrades-dpkg-log ] && \
    find /var/lib/misc/zabbix-check-upgrades-dpkg-log -mmin +360 -delete

# Only run if dpkg.log has changed
if [ /var/log/dpkg.log -ot /var/lib/misc/zabbix-check-upgrades-dpkg-log ]; then
    #echo "No changes in /var/log/dpkg.log"
    exit 0
fi

touch /var/lib/misc/zabbix-check-upgrades-dpkg-log

if [ "${RESTART_SERVICES}" = "yes" ]; then
    for service in $(/usr/sbin/needrestart -b -r l -l | awk ' /NEEDRESTART-SVC: / { print $2; }'); do
        logger -t $0 "Restarting $service"
        systemctl restart $service
    done
fi

VALUE=$(/usr/sbin/needrestart -b -r l -l | awk ' /NEEDRESTART-SVC: / { print $2; }' | tr "\n" "," | sed 's/,$//')
#echo "VALUE=${VALUE}"
/usr/bin/zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k "system.sw.needrestart.library" -o "${VALUE}" 1>/dev/null

if [ "${AUTOMATIC_REBOOT}" = "yes" ]; then
    NEEDRESTART_KSTA=$(/usr/sbin/needrestart -b -r l -k | awk ' /NEEDRESTART-KSTA:/ { print $2; }')
    DAY=$(date +%u)
    HOUR=$(date +%H)
    # Restart only on weekdays before 7am
    if [ ${NEEDRESTART_KSTA} -gt 1 ] && [ ${DAY} -lt 6 ] && [ ${HOUR} -lt 7 ] ; then
        logger -t $0 "Restarting system (reboot)"
        /sbin/reboot
    fi
fi

